### PR TITLE
feat(apps/interface): implement sharable page layout

### PR DESCRIPTION
**Pull request by math-marcellino**
Sharable page UI implementation

### CODE REVIEW

**Comment by asaadam** [comment]
@math-marcellino please change file name from `sharable` to `shareable`

and i think we should create test for this 

CC: @pyk

**Comment by math-marcellino** [comment]
Guys the UI is all done, please kindy check again, thank you! @asaadam @pyk 
cc: @ayikfour

**Review by asaadam — APPROVED** [review]
LGTM

**Comment by asaadam** [comment]
@math-marcellino since the element it's responsive, a different screen means when the user export, it will generate a different size too. 

I think we need to discuss this.  
since our image is generated based on the dom that is rendered on clients. 

CC : @pyk

**Comment by math-marcellino** [comment]
@pyk The test for `shareable` page is implemented and the test has passed. Let me know if there's something I missed, otherwise I think we can merge it :pray:

**Review by risedledev — APPROVED** [review]
LGTM @asaadam @math-marcellino

**Pull request merged**
