### PR TITLE
feat(apps/interface): set "Earn" href to open new tab to midas pool (temporary)

### PR DESCRIPTION
**Pull request by math-marcellino**
Change href for `earn` in navigation bar to https://app.midascapital.xyz/56/pool/6

### CODE REVIEW

**Comment by pyk** [comment]
@math-marcellino I think we need to at `ArrowTopRightIcon` too on Earn link

See example here

https://github.com/risedle/monorepo/blob/61f596725cd208834e08d18e6364367c2282399c/apps/interface/components/NavigationBarBottom/links.tsx#L102-L105

Also is it possible to pass `target="_blank" too? coz we want to open new tab if link clicked

**Comment by pyk** [comment]
@math-marcellino btw we need to update the test too for now:

https://github.com/risedle/monorepo/blob/61f596725cd208834e08d18e6364367c2282399c/apps/interface/tests/pages/trade/NavigationBarLinks.spec.tsx#L52

https://github.com/risedle/monorepo/blob/61f596725cd208834e08d18e6364367c2282399c/apps/interface/tests/pages/home/NavigationBarLinks.spec.tsx#L49

**Review by pyk — CHANGES_REQUESTED** [review]
See my comment above

**Comment by math-marcellino** [comment]
> @math-marcellino I think we need to at `ArrowTopRightIcon` too on Earn link
> 
> See example here
> 
> https://github.com/risedle/monorepo/blob/61f596725cd208834e08d18e6364367c2282399c/apps/interface/components/NavigationBarBottom/links.tsx#L102-L105
> 
> Also is it possible to pass `target="_blank"` too? coz we want to open new tab if link clicked

Okay got it sir, btw I think I have already used the `target="_blank"` here sir:

https://github.com/risedle/monorepo/blob/ris-481/apps/interface/components/NavigationBar/links.tsx#L12-L17

**Comment by math-marcellino** [comment]
> @math-marcellino btw we need to update the test too for now:
> 
> https://github.com/risedle/monorepo/blob/61f596725cd208834e08d18e6364367c2282399c/apps/interface/tests/pages/trade/NavigationBarLinks.spec.tsx#L52
> 
> https://github.com/risedle/monorepo/blob/61f596725cd208834e08d18e6364367c2282399c/apps/interface/tests/pages/home/NavigationBarLinks.spec.tsx#L49

I have fixed the test sir, please kindly check again 👍

**Review by pyk — APPROVED** [review]
LGTM. Thanks @math-marcellino 🔥

**Pull request merged**
