### PR TITLE
chore(apps/interface): refactor BackingCard AllocationTable

### PR DESCRIPTION
**Pull request by asaadam**
## Scope
List of affected projects:

- apps/interface

## Description
Currently the BackingCard [AllocationTable][1] is implemented as multiple VStack
stacked together.

We need to use Chakra `Table` component instead of using the div.

[1]: https://github.com/risedle/monorepo/blob/main/apps/interface/components/BackingCard/AllocationTable.tsx#L65

## Action items
Action items for this pull request:

- [X] Refactor the component to use `Table`
- [X] The generated component should spit out plain `<table>` element instead of div

## Checklist
You should check this before requesting for review:

- [X] Branch name use the the following format RIS-{NUMBER}
- [X] Pull request title is "chore(apps/interface): refactor BackingCard AllocationTable"
- [X] Make sure new files are 100% covered in [Risedle Code Coverage](https://coverage.risedle.com)

### CODE REVIEW

**Comment by asaadam** [comment]
image
updated preview @pyk

**Comment by pyk** [comment]
@asaadam can we remove the last bottom border? if not then lets merge this

**Comment by asaadam** [comment]
@pyk updated ser

**Review by pyk — APPROVED** [review]
Nice. Thanks @asaadam!

**Pull request merged**
